language: cpp
compiler: g++

install:
- yes "" | sudo add-apt-repository ppa:ubuntu-toolchain-r/test
- sudo apt-get update
- yes | sudo apt-get install g++-4.9 libglew-dev libopenal-dev libsndfile1-dev
- g++ --version
- sudo rm -rf /usr/bin/g++
- sudo ln -s /usr/bin/g++-4.9 /usr/bin/g++
- wget -O- http://heanet.dl.sourceforge.net/project/cbp2make/cbp2make-stl-rev147.tar.gz | tar xzf -
- cd cbp2make-stl-rev147/
- make -j9 -f cbp2make.cbp.mak.unix release
- cd ..
- wget http://www.sfml-dev.org/files/SFML-2.1-sources.zip
- unzip SFML-2.1-sources.zip
- cd SFML-2.1/
- cmake .
- sudo make -j9 install
- cd ..
- cd code/src/
- ../../cbp2make-stl-rev147/bin/Release/cbp2make -in robber.cbp -out Makefile



script:
- make -j9 linux
